#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$JENYCX_BNC_DATA_POSTGRES_ROOT_USER" --dbname "$JENYCX_BNC_DATA_POSTGRES_ROOT_DB" <<-EOSQL
	CREATE USER $JENYCX_BNC_DATA_POSTGRES_APP_USER WITH PASSWORD '$JENYCX_BNC_DATA_POSTGRES_APP_PASSWORD';
	CREATE DATABASE $JENYCX_BNC_DATA_POSTGRES_APP_DB;
	GRANT ALL PRIVILEGES ON DATABASE $JENYCX_BNC_DATA_POSTGRES_APP_DB TO $JENYCX_BNC_DATA_POSTGRES_APP_USER;
EOSQL